"""MORTIS report generation.

Produces the executive summary shown on the results page and in the
downloadable report. If an ANTHROPIC_API_KEY environment variable is set the
summary is generated by an LLM; otherwise it falls back to a deterministic
local summary so the app still works offline.
"""
import os
import re


def _strip_markdown(text: str) -> str:
    """Remove common Markdown markers so the summary reads as clean plain text
    in the report and results page (which display it verbatim).
    """
    text = re.sub(r"(?m)^\s{0,3}#{1,6}\s*", "", text)   # '# ' headings
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)          # **bold**
    text = re.sub(r"__(.+?)__", r"\1", text)              # __bold__
    text = re.sub(r"`([^`]+)`", r"\1", text)              # `code`
    text = re.sub(r"(?m)^\s*\*\s+", "- ", text)           # '* ' bullets -> '- '
    return text


def _local_summary(target_url: str, findings: list[dict], overall_rating: str) -> str:
    """Deterministic, offline summary. Also used as a fallback for the LLM."""
    risky = [f for f in findings if f.get("severity") in {"Medium", "High", "Critical"}]
    if not risky:
        return (
            f"MORTIS completed a baseline scan of {target_url}. No major issues were "
            "identified during this limited prototype scan. Further authenticated and "
            "deeper testing is still recommended."
        )

    top = sorted(risky, key=lambda f: f.get("score", 0), reverse=True)[:3]
    lines = [
        f"MORTIS completed a baseline scan of {target_url}.",
        f"Overall risk rating: {overall_rating}.",
        "The most important issues to review are:",
    ]
    for item in top:
        lines.append(f"- {item['title']} ({item['severity']}): {item['recommendation']}")
    lines.append(
        "This report is an initial draft and should be reviewed by a human tester "
        "before being used in a formal penetration-testing report."
    )
    return "\n".join(lines)


def _llm_summary(target_url: str, findings: list[dict], overall_rating: str, api_key: str) -> str:
    """Ask Claude to turn the findings into a clear, non-technical summary.

    Only non-sensitive finding metadata is transmitted (never raw scan bodies,
    cookies or tokens).
    """
    import anthropic

    client = anthropic.Anthropic(api_key=api_key)
    finding_lines = "\n".join(
        f"- {f.get('title')} ({f.get('severity')}): {f.get('description')}"
        for f in findings
    ) or "- No findings recorded."

    message = client.messages.create(
        model=os.environ.get("MORTIS_LLM_MODEL", "claude-sonnet-5"),
        max_tokens=800,
        system=(
            "You are a security report writer for a tool called MORTIS. Turn the "
            "supplied vulnerability findings into a concise executive summary that a "
            "non-technical reader can understand, followed by clear remediation steps. "
            "Do not invent findings that are not listed. "
            "Write in plain prose only. Do not use any Markdown formatting: no '#' "
            "headings, no '**' or '*' for emphasis, and no backticks. Use short "
            "paragraphs, and if you list items, start each line with '- '."
        ),
        messages=[{
            "role": "user",
            "content": (
                f"Target: {target_url}\n"
                f"Overall risk rating: {overall_rating}\n"
                f"Findings:\n{finding_lines}"
            ),
        }],
    )
    text = "".join(block.text for block in message.content if getattr(block, "type", "") == "text")
    return _strip_markdown(text.strip())


def generate_report_with_source(target_url: str, findings: list[dict],
                                overall_rating: str) -> tuple[str, str]:
    """Return (summary, source), where source is "api" when the LLM produced the
    summary or "offline" when the local fallback was used.
    """
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        return _local_summary(target_url, findings, overall_rating), "offline"
    try:
        return _llm_summary(target_url, findings, overall_rating, api_key), "api"
    except Exception:
        # Graceful degradation: never let a reporting/API error break a scan.
        return _local_summary(target_url, findings, overall_rating), "offline"


def generate_report(target_url: str, findings: list[dict], overall_rating: str) -> str:
    """Return just the executive summary text (used where the source is not needed)."""
    summary, _ = generate_report_with_source(target_url, findings, overall_rating)
    return summary
