"""MORTIS report generation.

Produces the executive summary shown on the results page and in the
downloadable report. If an ANTHROPIC_API_KEY environment variable is set the
summary is generated by an LLM; otherwise it falls back to a deterministic
local summary so the app still works offline.
"""
import os
import re

from markupsafe import Markup, escape

# Matches the fixed AI-disclaimer sentence, with or without surrounding brackets.
_DISCLAIMER_RE = re.compile(r"\[?(This summary was generated by an AI model.*?)\]?$", re.S)


def _strip_markdown(text: str) -> str:
    """Remove common Markdown markers so the summary reads as clean plain text
    (used for the .txt report, which has no formatting).
    """
    text = re.sub(r"(?m)^\s{0,3}#{1,6}\s*", "", text)     # '# ' headings
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)            # **bold**
    text = re.sub(r"__(.+?)__", r"\1", text)                # __bold__
    text = re.sub(r"`([^`]+)`", r"\1", text)                # `code`
    text = re.sub(r"(?m)^\s*\*\s+", "- ", text)             # '* ' bullets -> '- '
    text = re.sub(r"\[(This summary was generated by an AI model.*?)\]", r"\1", text)
    return text


def format_summary(text: str) -> Markup:
    """Render the stored summary as safe HTML for the results page and report:
    Markdown headings and **bold** become <strong>, and the AI disclaimer is
    shown in bold with its square brackets removed. Line breaks are preserved by
    the surrounding element's white-space styling.
    """
    if not text:
        return Markup("")

    out = []
    for line in text.split("\n"):
        s = line.strip()

        # Whole-line Markdown heading -> bold line.
        heading = re.match(r"^#{1,6}\s+(.*)$", s)
        if heading:
            out.append("<strong>" + str(escape(heading.group(1).strip())) + "</strong>")
            continue

        # The AI disclaimer line -> bold, brackets removed.
        disclaimer = _DISCLAIMER_RE.match(s)
        if disclaimer:
            out.append("<strong>" + str(escape(disclaimer.group(1).strip())) + "</strong>")
            continue

        esc = str(escape(s))
        esc = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", esc)   # **bold**
        esc = re.sub(r"__(.+?)__", r"<strong>\1</strong>", esc)       # __bold__
        esc = re.sub(r"^\*\s+", "- ", esc)                            # '* ' bullet -> '- '
        out.append(esc)

    return Markup("\n".join(out))


def _local_summary(target_url: str, findings: list[dict], overall_rating: str) -> str:
    """Deterministic, offline summary. Also used as a fallback for the LLM."""
    risky = [f for f in findings if f.get("severity") in {"Medium", "High", "Critical"}]
    if not risky:
        return (
            f"MORTIS completed a baseline scan of {target_url}. No major issues were "
            "identified during this limited prototype scan. Further authenticated and "
            "deeper testing is still recommended."
        )

    top = sorted(risky, key=lambda f: f.get("score", 0), reverse=True)[:3]
    lines = [
        f"MORTIS completed a baseline scan of {target_url}.",
        f"Overall risk rating: {overall_rating}.",
        "The most important issues to review are:",
    ]
    for item in top:
        lines.append(f"- {item['title']} ({item['severity']}): {item['recommendation']}")
    lines.append(
        "This report is an initial draft and should be reviewed by a human tester "
        "before being used in a formal penetration-testing report."
    )
    return "\n".join(lines)


def _llm_summary(target_url: str, findings: list[dict], overall_rating: str, api_key: str) -> str:
    """Ask Claude to turn the findings into a clear, non-technical summary.

    Only non-sensitive finding metadata is transmitted (never raw scan bodies,
    cookies or tokens).
    """
    import anthropic

    client = anthropic.Anthropic(api_key=api_key)
    finding_lines = "\n".join(
        f"- {f.get('title')} ({f.get('severity')}): {f.get('description')}"
        for f in findings
    ) or "- No findings recorded."

    message = client.messages.create(
        model=os.environ.get("MORTIS_LLM_MODEL", "claude-sonnet-5"),
        max_tokens=800,
        system=(
            "You are a security report writer for a tool called MORTIS. Turn the "
            "supplied vulnerability findings into a concise executive summary that a "
            "non-technical reader can understand, followed by clear remediation steps. "
            "Do not invent findings that are not listed. "
            "Structure the summary with short section headings written on their own "
            "line starting with '## ' (for example '## Overview' and '## Recommended "
            "Actions'). Use '**' around key terms you want emphasised, and start list "
            "items with '- '. Do not use any other Markdown, tables, or backticks."
        ),
        messages=[{
            "role": "user",
            "content": (
                f"Target: {target_url}\n"
                f"Overall risk rating: {overall_rating}\n"
                f"Findings:\n{finding_lines}"
            ),
        }],
    )
    text = "".join(block.text for block in message.content if getattr(block, "type", "") == "text")
    # Keep the Markdown here; it is rendered to HTML (or stripped for .txt) at display time.
    return text.strip() + (
        "\n\n[This summary was generated by an AI model and must be reviewed by a "
        "human tester before being used in a formal penetration-testing report.]"
    )


def generate_report_with_source(target_url: str, findings: list[dict],
                                overall_rating: str) -> tuple[str, str]:
    """Return (summary, source), where source is "api" when the LLM produced the
    summary or "offline" when the local fallback was used.
    """
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        return _local_summary(target_url, findings, overall_rating), "offline"
    try:
        return _llm_summary(target_url, findings, overall_rating, api_key), "api"
    except Exception:
        # Graceful degradation: never let a reporting/API error break a scan.
        return _local_summary(target_url, findings, overall_rating), "offline"


def generate_report(target_url: str, findings: list[dict], overall_rating: str) -> str:
    """Return just the executive summary text (used where the source is not needed)."""
    summary, _ = generate_report_with_source(target_url, findings, overall_rating)
    return summary
